### ISSUE TITLE
wss

### ISSUE THREAD

**Issue by mahon7474** [ArturSpirin/test_junkie#33]
I found it very difficult to find a way to write to you!
I saw some of your published videos, more specifically about browsermob-proxy.
i want to ask if it can record socket traffic flowing in the browser, by the method you showed.
i want to save socket data but it is encrypted by traffic, is there any way to get it directly from the browser?
thanks
Regards 
mahon74@abv.bg

**Comment by ArturSpirin** [comment]
@mahon7474 If you want to reach me directly you can write to me on Linked In. Otherwise you can leave a comment under the YouTube video and I will try to get back to you.

Regarding your question, the most direct way would be to use dev tools for chrome. https://developers.google.com/web/tools/chrome-devtools/network and there are Python libraries available that allow you to easily work with dev tools on chrome and they can be used with Selenium. So I suggest you direct your research towards dev tools.
